config/routes.rb
Rails.application.routes.draw do
  resources :tails

  root 'tails#index'

end

app/models/tail.rb
class Tail < ActiveRecord::Base
  validates :title, length: { maximum: 140 }, presence: true
  validates :teller, length: { maximum: 70 }
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tails_controller.rb
class TailsController < ApplicationController
  before_action :set_tail, only: [:show, :edit, :update, :destroy]

  # GET /tails
  # GET /tails.json
  def index
    @tails = Tail.all
  end

  # GET /tails/1
  # GET /tails/1.json
  def show
  end

  # GET /tails/new
  def new
    @tail = Tail.new
  end

  # GET /tails/1/edit
  def edit
  end

  # POST /tails
  # POST /tails.json
  def create
    @tail = Tail.new(tail_params)

    respond_to do |format|
      if @tail.save
        format.html { redirect_to @tail, notice: 'Tail was successfully created.' }
        format.json { render :show, status: :created, location: @tail }
      else
        format.html { render :new }
        format.json { render json: @tail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tails/1
  # PATCH/PUT /tails/1.json
  def update
    respond_to do |format|
      if @tail.update(tail_params)
        format.html { redirect_to @tail, notice: 'Tail was successfully updated.' }
        format.json { render :show, status: :ok, location: @tail }
      else
        format.html { render :edit }
        format.json { render json: @tail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tails/1
  # DELETE /tails/1.json
  def destroy
    @tail.destroy
    respond_to do |format|
      format.html { redirect_to tails_url, notice: 'Tail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tail
      @tail = Tail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tail_params
      params.require(:tail).permit(:title, :content, :teller)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tails_helper.rb
module TailsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HauntedOffice</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tails/_form.html.slim
= form_for @tail, html: { class: "form form-horizontal tail" } do |f|
  .form-group
    = f.label :title, :class => 'control-label col-lg-4'
    .col-lg-10
      = f.text_field :title, :class => 'form-control'
    = f.error_span(:title)
  .form-group
    = f.label :content, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_area :content, :class => 'form-control', :size => '80x6'
    = f.error_span(:content)
  .form-group
    = f.label :teller, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :teller, :class => 'form-control'
    = f.error_span(:teller)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil, :class => 'btn btn-primary'
      '
      = link_to t('.cancel', :default => t("helpers.links.cancel")), tails_path, :class => 'btn'

app/views/tails/edit.html.slim
- model_class = Tail
.page-header
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/tails/index.html.slim
- model_class = Tail
.page-header
  h1 エンジニア百物語

hr

p
  |
    ようこそ、エンジニアが集う長屋へ。「怖い話」が百に達した時、何かが起こる…?

hr

table.table.table-striped
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:title)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @tails.reverse.each do |tail|
      tr
        td= tail.id
        td.title = link_to tail.title, tail_path(tail)
        td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_tail_path(tail), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), tail_path(tail), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

hr

= link_to '怪談を話す', new_tail_path, :class => 'btn btn-primary'

app/views/tails/new.html.slim
- model_class = Tail
.page-header
  h1. 怪談を話す
= render :partial => "form"

app/views/tails/show.html.slim
- model_class = Tail
.page-header
  h1= @tail.title

p
  br
  = @tail.content
p.teller
  br
  - unless @tail.teller.blank?
    = '- ' + @tail.teller

= link_to t('.back', :default => t("helpers.links.back")), tails_path, :class => 'btn btn-default'
'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_tail_path(@tail), :class => 'btn btn-default'
'
= link_to t('.destroy', :default => t("helpers.links.destroy")), tail_path(@tail), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'